### ISSUE TITLE
Autocomplete for full systematic name does not return that gene

### ISSUE THREAD

**Issue by cgreene** [greenelab/py3-adage-backend#24]
Test:

autocomplete for `PA0985`. Results returned do not include pyoS5

![Screen Shot 2019-12-18 at 11 07 29 AM](https://user-images.githubusercontent.com/542643/71102499-9d808000-2186-11ea-91c1-1b078ec97e72.png)

**Comment by dongbohu** [comment]
The results returned directly from the API:
https://py3-adage.greenelab.com/api/v1/gene/?autocomplete=pa0985

`PA0985` is ranked `#8` instead of `#1`. Here is the reason: In current trigram search, the results are ranked by the sum of the matching scores of `standard_name`, `systematic_name`, `description` and `extrezid`. Although none of the results in `#1-#7` are exact matches, their standard and systematic names have good partial matches. So the sums of matching scores in `#1-#7` are higher than that in `#8`. 

To fix this problem, the search results can be ranked first by maximum matching score, then the sum of all matching scores. What do you think, @cgreene?

**Comment by cgreene** [comment]
I do think that'd be a good thing to use for ranking because an exact match seems like it should be returned at the top. We can see how it performs and if folks end up complaining.

**Comment by dongbohu** [comment]
Sure. I will file a PR soon.

**Comment by dongbohu** [comment]
Fixed by PR #25.
